name: ekotrack
description: "Your new Flutter project"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.1
  flutter_map_marker_popup: ^8.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  latlong2: ^0.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  # fonts:
  #   - family: GoogleSans
  #     fonts:
  #       - asset: assets/fonts/GoogleSans-Regular.ttf

